# -*- coding: utf-8 -*-
"""直招岗位表爬取.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PRNgGV3Ri24Rz5CFtyM6qq6uCrFHSpu_
"""

from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import requests as re
import time

# 2022: 211.166.76.109:9998
# 2023: 111.203.147.109:9998
url = lambda i:"http://111.203.147.109:9998/enroll/post/listVisitor?page="+str(i)+"&limit=50&queryStr="

p = pd.DataFrame()

i = 1
while i < 61:
    try:
        tempD = re.get(url(int(i)))
    except:
        continue
    print('第{}页获取完成'.format(i))
    i += 1
    for j in tempD.json()['data']['data']:
        try:
            p = pd.concat([p,pd.json_normalize(j)])
        except Exception as e:
            print(type(e))
    time.sleep(1)

d = p.drop_duplicates()
d.to_excel('info.xlsx')

